spring:
  application:
    name: zuul-gateway
server:
  port: 5555

                                                           #传统路由的实现方式
zuul:
  routes:
    hello-url:                                        #这里的"hello-url"是路由的名字，可以自定义，同一个跳转的path和url的路由名称要相同
      path: /hello-url/**                        #映射的url
      url: http://localhost:9001/           #被映射的url